# Generated by Django 2.1.7 on 2019-03-20 16:48

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usr_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='initsys.Usr')),
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('CURP', models.CharField(max_length=18)),
                ('RFC', models.CharField(max_length=13)),
                ('NSS', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado'), ('Soltero', 'Soltero'), ('UnionLibre', 'Unión Libre'), ('Viudo', 'Viudo')], default='Casado', max_length=15)),
                ('empresa', models.CharField(max_length=150)),
                ('telefono_oficina', models.CharField(blank=True, max_length=10, verbose_name='Teléfono de oficina')),
                ('otro_telefono', models.CharField(blank=True, max_length=10, verbose_name='Otro teléfono')),
                ('afore_actual', models.CharField(max_length=50)),
                ('fecha_afore_actual', models.DateField(blank=True)),
                ('domicilicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='initsys.Direccion')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'apellido_materno'],
            },
            bases=('initsys.usr',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomiaExpediente',
            fields=[
                ('idtaxonomia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='app.TaxonomiaExpediente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['padre', 'nombre'],
            },
        ),
    ]
