# Generated by Django 2.1.7 on 2019-04-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190328_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='app.TaxonomiaExpediente'),
            preserve_default=False,
        ),
    ]
