# Generated by Django 2.0.7 on 2019-04-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cliente_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomiaexpediente',
            options={'ordering': ['nombre']},
        ),
    ]
