# Generated by Django 2.1.7 on 2019-04-07 05:18

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0001_initial'),
        ('app', '0004_auto_20190406_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctoGral',
            fields=[
                ('iddoctogral', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Acta de Nacimiento', 'Acta de Nacimiento'), ('Carta a Dirección de Prestaciones Económicas', 'Carta a Dirección de Prestaciones Económicas'), ('Carta de AFORE', 'Carta de AFORE'), ('Carta de Inscripción MOD40', 'Carta de Inscripción MOD40'), ('Clave de Acceso a Sistema de Reporte de Semanas Cotizadas', 'Clave de Acceso a Sistema de Reporte de Semanas Cotizadas'), ('Corrección en IMSS', 'Corrección en IMSS'), ('Corrección en Procesar', 'Corrección en Procesar'), ('CURP', 'CURP'), ('Estado de Cuenta Afore', 'Estado de Cuenta Afore'), ('IMSS', 'IMSS'), ('INE', 'INE'), ('Reporte de Semanas Cotizadas', 'Reporte de Semanas Cotizadas'), ('RFC', 'RFC')], default='Acta de Nacimiento', max_length=100)),
                ('mimetype_anverso', models.CharField(max_length=50)),
                ('anverso', models.FileField(upload_to=app.models.docto_upload_to)),
                ('mimetype_reverso', models.CharField(blank=True, max_length=50)),
                ('reverso', models.FileField(blank=True, upload_to=app.models.docto_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['tipo', 'iddoctogral'],
            },
        ),
    ]
