# Generated by Django 2.1.7 on 2019-04-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctogral'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctogral',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
