# Generated by Django 2.1.7 on 2019-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctogral_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clinica',
            field=models.CharField(blank=True, max_length=150, verbose_name='Clínica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conyuge',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='subdelegacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='Subdelegación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CURP',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='NSS',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='RFC',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='afore_actual',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
