# Generated by Django 2.1.7 on 2019-04-10 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cliente_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_afore_actual',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Fecha de nacimiento'),
        ),
    ]
