# Generated by Django 2.0.7 on 2019-04-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190406_0143'),
        ('app', '0009_auto_20190409_1953'),
    ]

    operations = [
    ]
