# Generated by Django 2.1.7 on 2019-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190416_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatusactividad',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Ninguno'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomiaexpediente',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Ninguno'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='', max_length=50),
        ),
    ]
