# Generated by Django 2.1.7 on 2019-04-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190417_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctogral',
            options={'ordering': ['tipo_de_documento', 'iddoctogral']},
        ),
    ]
