# Generated by Django 2.0.7 on 2019-04-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_merge_20190409_1957'),
        ('app', '0012_auto_20190417_0138'),
    ]

    operations = [
    ]
