# Generated by Django 2.1.7 on 2019-05-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0002_auto_20190409_1910'),
        ('app', '0014_actividad_historialaboral_historialaboralregistro_historialaboralregistrodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadHistoria',
            fields=[
                ('idactividadhistoria', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='comenatrios',
            new_name='comentarios',
        ),
        migrations.AddField(
            model_name='actividad',
            name='responsable',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='actividadhistoria',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle', to='app.Actividad'),
        ),
        migrations.AddField(
            model_name='actividadhistoria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
        migrations.AddField(
            model_name='actividadhistoria',
            name='estado_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.EstatusActividad'),
        ),
        migrations.AddField(
            model_name='actividadhistoria',
            name='estado_nuevo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.EstatusActividad'),
        ),
        migrations.AddField(
            model_name='actividadhistoria',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
    ]
