# Generated by Django 2.1.7 on 2019-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190514_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
