# Generated by Django 2.1.7 on 2019-05-21 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190521_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadhistoria',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app.Actividad'),
        ),
    ]
