# Generated by Django 2.1.7 on 2019-05-28 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0002_auto_20190409_1910'),
        ('app', '0017_auto_20190521_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('idexterno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['nombre', 'apellido_paterno', 'apellido_materno'],
            },
        ),
        migrations.AlterField(
            model_name='actividad',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resp_actividades', to='app.Externo'),
        ),
    ]
