# Generated by Django 2.1.7 on 2019-06-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190528_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialaboral',
            old_name='comenatrios',
            new_name='comentarios',
        ),
    ]
