# Generated by Django 2.1.7 on 2019-06-12 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190607_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialaboralregistrodetalle',
            name='vigente',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='historialaboralregistrodetalle',
            name='fecha_final',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
