# Generated by Django 2.1.7 on 2019-06-12 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190612_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialaboralregistro',
            name='fecha_de_alta',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='historialaboralregistro',
            name='fecha_de_baja',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
