# Generated by Django 2.1.7 on 2019-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190611_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialaboralregistro',
            name='vigente',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
