# Generated by Django 2.1.7 on 2019-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190612_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialaboralregistro',
            name='fecha_de_alta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialaboralregistro',
            name='fecha_de_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
