# Generated by Django 2.1.7 on 2019-06-18 04:09

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190617_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uma',
            options={'ordering': ['-año']},
        ),
        migrations.AddField(
            model_name='historialaboral',
            name='uma',
            # field=models.ForeignKey(default=app.models.getmaxUMA, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.UMA'),
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.UMA'),
        ),
    ]
