# Generated by Django 2.1.7 on 2019-06-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0002_auto_20190409_1910'),
        ('app', '0028_auto_20190617_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuantiabasica',
            fields=[
                ('idcuantia', models.AutoField(primary_key=True, serialize=False)),
                ('salario_inicio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('salario_fin', models.DecimalField(decimal_places=4, max_digits=6)),
                ('porcentaje_de_cuantia_basica', models.DecimalField(decimal_places=3, max_digits=5)),
                ('porcentaje_de_incremento_anual', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['salario_inicio', 'salario_fin'],
            },
        ),
        migrations.CreateModel(
            name='Factoredad',
            fields=[
                ('idfactoredad', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.PositiveSmallIntegerField()),
                ('factor_de_edad', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['edad'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['last_name', 'apellido_materno', 'first_name']},
        ),
        migrations.AlterField(
            model_name='externo',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='externo',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
