# Generated by Django 2.1.7 on 2019-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190619_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoredad',
            name='factor_de_edad',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
