# Generated by Django 2.1.7 on 2019-06-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190619_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLRDDay',
            fields=[
                ('idhlrdday', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('historialaboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlrd_days_hl', to='app.HistoriaLaboral')),
                ('historialaboralregistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlrd_days_reg', to='app.HistoriaLaboralRegistro')),
                ('historialaboralregistrodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlrd_days_det', to='app.HistoriaLaboralRegistroDetalle')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
