# Generated by Django 2.1.7 on 2019-06-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_hlrdday'),
    ]

    operations = [
        migrations.CreateModel(
            name='HLRD_periodo_continuo_laborado',
            fields=[
                ('idhlrdday', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveSmallIntegerField()),
                ('semanas', models.PositiveIntegerField()),
                ('historialaboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlrd_periodos_continuo_hl', to='app.HistoriaLaboral')),
                ('historialaboralregistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hlrd_periodos_continuo_reg', to='app.HistoriaLaboralRegistro')),
            ],
        ),
    ]
