# Generated by Django 2.1.7 on 2019-06-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190624_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialaboral',
            name='dias_salario_promedio',
            field=models.PositiveSmallIntegerField(default=1750, verbose_name='Cantidad de Días para calculo de salario promedio'),
        ),
    ]
