# Generated by Django 2.1.7 on 2019-06-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_historialaboral_dias_salario_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='anios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='anios_cotiz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='anios_inact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='dias_cotiz',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='dias_inact',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='semanas_cotiz',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hlrd_periodo_continuo_laborado',
            name='semanas_inact',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
