# Generated by Django 2.1.7 on 2019-07-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190627_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hlrd_periodo_continuo_laborado',
            name='historialaboral',
        ),
        migrations.RemoveField(
            model_name='hlrd_periodo_continuo_laborado',
            name='historialaboralregistro',
        ),
        migrations.RemoveField(
            model_name='hlrd_periodo_continuo_laborado_levelhl',
            name='historialaboral',
        ),
        migrations.RemoveField(
            model_name='hlrdday',
            name='historialaboral',
        ),
        migrations.RemoveField(
            model_name='hlrdday',
            name='historialaboralregistro',
        ),
        migrations.RemoveField(
            model_name='hlrdday',
            name='historialaboralregistrodetalle',
        ),
        migrations.DeleteModel(
            name='HLRD_periodo_continuo_laborado',
        ),
        migrations.DeleteModel(
            name='HLRD_periodo_continuo_laborado_levelhl',
        ),
        migrations.DeleteModel(
            name='HLRDDay',
        ),
    ]
