# Generated by Django 2.1.7 on 2019-07-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0003_auto_20190723_1358'),
        ('app', '0036_auto_20190707_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionPension',
            fields=[
                ('idopcionpension', models.AutoField(primary_key=True, serialize=False)),
                ('seleccionada', models.BooleanField(default=False)),
                ('salario_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('dias_calculo_saldo_promedio', models.PositiveSmallIntegerField()),
                ('semanas_cotizadas', models.PositiveSmallIntegerField()),
                ('porcentaje_cuantia_basica', models.DecimalField(decimal_places=3, max_digits=6)),
                ('porcentaje_incremento_anual', models.DecimalField(decimal_places=3, max_digits=6)),
                ('edad', models.PositiveSmallIntegerField()),
                ('porcentaje_factor_edad', models.DecimalField(decimal_places=3, max_digits=6)),
                ('porcentaje_esposa', models.DecimalField(decimal_places=3, max_digits=6)),
                ('porcentaje_hijos', models.DecimalField(decimal_places=3, max_digits=6)),
                ('porcentaje_asignaciones_familiares', models.DecimalField(decimal_places=3, max_digits=6)),
                ('pension_mensual_calculada', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('comentarios', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['seleccionada', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='historialaboral',
            name='factor_de_actualizacion',
            field=models.DecimalField(decimal_places=2, default=1.11, max_digits=5, verbose_name='Factor de Actualización'),
        ),
        migrations.AddField(
            model_name='historialaboral',
            name='numero_de_hijos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de Hijos'),
        ),
        migrations.AddField(
            model_name='historialaboral',
            name='tiene_esposa',
            field=models.BooleanField(default=False, verbose_name='¿Tiene esposa?'),
        ),
        migrations.AddField(
            model_name='opcionpension',
            name='historia_laboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app.HistoriaLaboral'),
        ),
        migrations.AddField(
            model_name='opcionpension',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
    ]
