# Generated by Django 2.1.7 on 2019-07-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190729_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionpension',
            name='uma_anio',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcionpension',
            name='uma_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
