# Generated by Django 2.1.7 on 2019-07-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20190729_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionpension',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=3, default=11, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcionpension',
            name='porcentaje_cuantia_basica_incremento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcionpension',
            name='porcentaje_de_salario_promedio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opcionpension',
            name='salario_promedio_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='historialaboral',
            name='factor_de_actualizacion',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5, verbose_name='Factor de Actualización'),
        ),
    ]
