# Generated by Django 2.1.7 on 2019-07-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190729_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionpension',
            options={'ordering': ['-seleccionada', '-created_at']},
        ),
    ]
