# Generated by Django 2.0.7 on 2019-08-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190730_1709'),
        ('app', '0040_auto_20190730_1851'),
    ]

    operations = [
    ]
