# Generated by Django 2.1.7 on 2019-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190813_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialaboral',
            name='factor_de_actualizacion',
            field=models.DecimalField(decimal_places=2, default=1.11, max_digits=5, verbose_name='Factor de Actualización'),
        ),
    ]
