# Generated by Django 2.0.7 on 2019-08-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190813_1658'),
        ('app', '0041_merge_20190812_1358'),
    ]

    operations = [
    ]
