# Generated by Django 2.1.7 on 2019-09-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0003_auto_20190723_1358'),
        ('app', '0042_auto_20190820_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaLaboralRegistroDetalleSupuesto',
            fields=[
                ('idhistorialaboralregistrodetalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField(null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(blank=True, default=False)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['historia_laboral_registro_supuesto', '-fecha_inicial', '-fecha_final'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaLaboralRegistroSupuesto',
            fields=[
                ('idhistorialaboralregistrosupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('registro_patronal', models.CharField(blank=True, max_length=15)),
                ('empresa', models.CharField(blank=True, default='Supuesto', max_length=200)),
                ('fecha_de_alta', models.DateField(blank=True, null=True)),
                ('fecha_de_baja', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('historia_laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_supuesto', to='app.HistoriaLaboral')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['historia_laboral', '-fecha_de_alta', '-fecha_de_baja'],
            },
        ),
        migrations.AddField(
            model_name='historialaboralregistrodetallesupuesto',
            name='historia_laboral_registro_supuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app.HistoriaLaboralRegistroSupuesto'),
        ),
        migrations.AddField(
            model_name='historialaboralregistrodetallesupuesto',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr'),
        ),
    ]
