# Generated by Django 2.0.7 on 2019-08-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_merge_20190813_1811'),
        ('app', '0042_auto_20190820_1050'),
    ]

    operations = [
    ]
