# Generated by Django 2.1.7 on 2019-09-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190917_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcionpension',
            options={'ordering': ['-seleccionada', 'created_at']},
        ),
        migrations.AlterField(
            model_name='historialaboralregistrosupuesto',
            name='registro_patronal',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
