# Generated by Django 2.0.7 on 2019-09-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_merge_20190820_1053'),
        ('app', '0043_auto_20190917_1421'),
    ]

    operations = [
    ]
