# Generated by Django 2.0.7 on 2019-09-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_merge_20190919_1959'),
        ('app', '0044_auto_20190923_1711'),
    ]

    operations = [
    ]
