# Generated by Django 2.1.7 on 2019-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_merge_20190924_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='obs_duplicidad',
            field=models.TextField(blank=True, verbose_name='Duplicidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='obs_homonimia',
            field=models.TextField(blank=True, verbose_name='Homonimia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='obs_semanas_cotizadas',
            field=models.TextField(blank=True, verbose_name='Semanas Cotizadas'),
        ),
    ]
