# Generated by Django 3.0.2 on 2020-01-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0003_auto_20190723_1358'),
        ('app', '0047_assocacttarea_assocctetarea_assochistlabtarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to='initsys.Usr'),
        ),
    ]
