# Generated by Django 3.0.2 on 2020-01-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_cliente_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Responsable',
            new_name='responsable',
        ),
    ]
