# Generated by Django 3.0.4 on 2020-10-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0003_auto_20190723_1358'),
        ('app', '0050_actividad_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_liquidado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MedioActividad',
            fields=[
                ('idmedioctividad', models.AutoField(primary_key=True, serialize=False)),
                ('medio', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='initsys.Usr')),
            ],
            options={
                'ordering': ['medio'],
            },
        ),
    ]
