# Generated by Django 3.0.4 on 2020-10-12 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20201012_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='medio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_con_medio', to='app.MedioActividad'),
            preserve_default=False,
        ),
    ]
