# Generated by Django 3.0.4 on 2021-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_actividad_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialaboral',
            name='semanas_descontar',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de Semanas a Descontar'),
        ),
        migrations.AddField(
            model_name='historialaboralregistro',
            name='color',
            field=models.CharField(choices=[('', 'Ninguno'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='secondary', max_length=15),
        ),
        migrations.AddField(
            model_name='historialaboralregistrosupuesto',
            name='color',
            field=models.CharField(choices=[('', 'Ninguno'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark')], default='primary', max_length=15),
        ),
    ]
