# Generated by Django 3.0.4 on 2021-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20210224_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialaboral',
            name='semanas_descontar',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Número de Semanas a Descontar'),
        ),
    ]
