# Generated by Django 3.0.4 on 2021-03-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0003_auto_20190723_1358'),
        ('app', '0055_auto_20210224_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_gestionados', to='initsys.Usr', verbose_name='Gestor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to='initsys.Usr', verbose_name='Ejecutivo'),
        ),
    ]
