# Generated by Django 3.0.7 on 2021-03-15 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20210309_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpReporteControlInscritosMod40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estimada_de_baja', models.DateField(default=datetime.date.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Cliente')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.MedioActividad')),
            ],
            options={
                'ordering': ['fecha_estimada_de_baja'],
            },
        ),
        migrations.CreateModel(
            name='TmpReportPensionesEnProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_envio', models.DateField(default=datetime.date.today)),
                ('fecha_de_pago_inicial', models.DateField(default=datetime.date.today)),
                ('fecha_de_retiro_total', models.DateField(default=datetime.date.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Cliente')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.MedioActividad')),
            ],
            options={
                'ordering': ['fecha_de_envio'],
            },
        ),
        migrations.CreateModel(
            name='TmpReportTramitesYCorrecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_envio', models.DateField(default=datetime.date.today)),
                ('fecha_de_conclusion', models.DateField(default=datetime.date.today)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('fecha_de_liquidacion', models.DateField(default=datetime.date.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Cliente')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.MedioActividad')),
                ('tipo_de_tramite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.TipoActividad')),
            ],
            options={
                'ordering': ['fecha_de_envio'],
            },
        ),
        migrations.CreateModel(
            name='TmpReportPensionesEnProcesoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prorroga_o_incorformidad', models.CharField(max_length=250)),
                ('fecha_de_envio', models.DateField(default=datetime.date.today)),
                ('fecha_de_correccion', models.DateField(default=datetime.date.today)),
                ('raiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app.TmpReportPensionesEnProceso')),
            ],
            options={
                'ordering': ['fecha_de_envio'],
            },
        ),
        migrations.CreateModel(
            name='TmpReporteControlRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_ultimo_contacto', models.DateField(default=datetime.date.today)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Cliente')),
            ],
            options={
                'ordering': ['fecha_de_ultimo_contacto'],
            },
        ),
        migrations.CreateModel(
            name='TmpReporteControlProximoPensionMod40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_del_evento', models.DateField(default=datetime.date.today)),
                ('tipo', models.CharField(choices=[('Pensión', 'Pension'), ('MOD 40', 'MOD 40')], default='Pensión', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Cliente')),
            ],
            options={
                'ordering': ['tipo', 'fecha_del_evento'],
            },
        ),
        migrations.CreateModel(
            name='TmpReporteControlPatronSustitutoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.DateField(default=datetime.date.today)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('raiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app.TmpReporteControlPatronSustitutoDetalle')),
            ],
            options={
                'ordering': ['fecha_de_pago'],
            },
        ),
        migrations.CreateModel(
            name='TmpReporteControlPatronSustituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_alta', models.DateField(default=datetime.date.today)),
                ('fecha_estimada_de_baja', models.DateField(default=datetime.date.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Cliente')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.MedioActividad')),
            ],
            options={
                'ordering': ['fecha_de_alta'],
            },
        ),
        migrations.CreateModel(
            name='TmpReporteControlInscritosMod40Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_pago', models.DateField(default=datetime.date.today)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('linea_de_captura', models.CharField(max_length=100)),
                ('estatus_de_envio', models.CharField(choices=[('Enviado', 'Enviado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=15)),
                ('raiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='app.TmpReporteControlInscritosMod40')),
            ],
            options={
                'ordering': ['fecha_de_pago'],
            },
        ),
    ]
