ESTADO_CIVIL_SOLTERO = "Soltero"
ESTADO_CIVIL_CASADO = "Casado"
ESTADO_CIVIL_UNION_LIBRE = "UnionLibre"
ESTADO_CIVIL_SEPARADO = "Separado"
ESTADO_CIVIL_DIVORCIADO = "Divorciado"
ESTADO_CIVIL_VIUDO = "Viudo"
ESTADOS_CIVILES = (
    (ESTADO_CIVIL_CASADO, "Casado"),
    (ESTADO_CIVIL_DIVORCIADO, "Divorciado"),
    (ESTADO_CIVIL_SEPARADO, "Separado"),
    (ESTADO_CIVIL_SOLTERO, "Soltero"),
    (ESTADO_CIVIL_UNION_LIBRE, "Unión Libre"),
    (ESTADO_CIVIL_VIUDO, "Viudo"),
)


TIPO_DOCUMENTO_GRAL_ACTA_DE_NACIMIENTO = 'Acta de Nacimiento'
TIPO_DOCUMENTO_GRAL_CURP = 'CURP'
TIPO_DOCUMENTO_GRAL_INE = 'INE'
TIPO_DOCUMENTO_GRAL_RFC = 'RFC'
TIPO_DOCUMENTO_GRAL_IMSS = 'IMSS'
TIPO_DOCUMENTO_GRAL_ESTADO_DE_CUENTA_AFORE = 'Estado de Cuenta Afore'
TIPO_DOCUMENTO_GRAL_CARTA_A_DIRECCION_DE_PRESTACIONES_ECONOMICAS = \
    'Carta a Dirección de Prestaciones Económicas'
TIPO_DOCUMENTO_GRAL_CARTA_DE_INSCRIPCION_MOD40 = \
    'Carta de Inscripción MOD40'
TIPO_DOCUMENTO_GRAL_CARTA_DE_AFORE = 'Carta de AFORE'
TIPO_DOCUMENTO_GRAL_CLAVE_DE_ACCESO_A_SISTEMA_REPORTE_SEMANAS_COTIZADAS = \
    'Clave de Acceso a Sistema de Reporte de Semanas Cotizadas'
TIPO_DOCUMENTO_GRAL_CORRECCION_EN_PROCESAR = 'Corrección en Procesar'
TIPO_DOCUMENTO_GRAL_CORRECCION_EN_IMSS = 'Corrección en IMSS'
TIPO_DOCUMENTO_GRAL_REPORTE_DE_SEMANAS_COTIZADAS = \
    'Reporte de Semanas Cotizadas'
TIPOS_DOCUMENTO_GRAL = (
  (
    TIPO_DOCUMENTO_GRAL_ACTA_DE_NACIMIENTO,
    TIPO_DOCUMENTO_GRAL_ACTA_DE_NACIMIENTO
  ),
  (
    TIPO_DOCUMENTO_GRAL_CARTA_A_DIRECCION_DE_PRESTACIONES_ECONOMICAS,
    TIPO_DOCUMENTO_GRAL_CARTA_A_DIRECCION_DE_PRESTACIONES_ECONOMICAS
  ),
  (
    TIPO_DOCUMENTO_GRAL_CARTA_DE_AFORE,
    TIPO_DOCUMENTO_GRAL_CARTA_DE_AFORE
  ),
  (
    TIPO_DOCUMENTO_GRAL_CARTA_DE_INSCRIPCION_MOD40,
    TIPO_DOCUMENTO_GRAL_CARTA_DE_INSCRIPCION_MOD40
  ),
  (
    TIPO_DOCUMENTO_GRAL_CLAVE_DE_ACCESO_A_SISTEMA_REPORTE_SEMANAS_COTIZADAS,
    TIPO_DOCUMENTO_GRAL_CLAVE_DE_ACCESO_A_SISTEMA_REPORTE_SEMANAS_COTIZADAS
  ),
  (
    TIPO_DOCUMENTO_GRAL_CORRECCION_EN_IMSS,
    TIPO_DOCUMENTO_GRAL_CORRECCION_EN_IMSS
  ),
  (
    TIPO_DOCUMENTO_GRAL_CORRECCION_EN_PROCESAR,
    TIPO_DOCUMENTO_GRAL_CORRECCION_EN_PROCESAR
  ),
  (
    TIPO_DOCUMENTO_GRAL_CURP,
    TIPO_DOCUMENTO_GRAL_CURP
  ),
  (
    TIPO_DOCUMENTO_GRAL_ESTADO_DE_CUENTA_AFORE,
    TIPO_DOCUMENTO_GRAL_ESTADO_DE_CUENTA_AFORE
  ),
  (
    TIPO_DOCUMENTO_GRAL_IMSS,
    TIPO_DOCUMENTO_GRAL_IMSS
  ),
  (
    TIPO_DOCUMENTO_GRAL_INE,
    TIPO_DOCUMENTO_GRAL_INE
  ),
  (
    TIPO_DOCUMENTO_GRAL_REPORTE_DE_SEMANAS_COTIZADAS,
    TIPO_DOCUMENTO_GRAL_REPORTE_DE_SEMANAS_COTIZADAS
  ),
  (
    TIPO_DOCUMENTO_GRAL_RFC,
    TIPO_DOCUMENTO_GRAL_RFC
  ),
)
