# Generated by Django 2.1.7 on 2019-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='colonia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alcaldía o Municipio'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_exterior',
            field=models.CharField(blank=True, max_length=10, verbose_name='No. Exterior'),
        ),
    ]
