# Generated by Django 2.1.7 on 2019-07-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initsys', '0002_auto_20190409_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usr',
            options={'ordering': ['first_name', 'last_name', 'apellido_materno']},
        ),
    ]
