# Generated by Django 2.1.7 on 2019-12-10 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tarea', 'created_at', 'idcomentario'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('idhistoria', models.AutoField(primary_key=True, serialize=False)),
                ('cambio', models.CharField(max_length=250)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tarea', 'created_at', 'idhistoria'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_limite', models.DateField(default=datetime.date.today, verbose_name='Fecha límite')),
                ('estado_actual', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN PROGRESO', 'EN PROGRESO'), ('EN REVISION', 'EN REVISION'), ('REALIZADO', 'REALIZADO'), ('CANCELADO', 'CANCELADO'), ('OTRO', 'OTRO')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'ordering': ['idtarea'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('idvinculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinclulos', to='simple_tasks.Tarea')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tarea', 'tipo', 'texto'],
            },
        ),
        migrations.AddField(
            model_name='historia',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='simple_tasks.Tarea'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='simple_tasks.Tarea'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
